environment:
  agent:
    llm:
      config_name: vllm
    social_memory:
      reflection: false
      summary_threshold: 10
      type: social_memory
    type: article_agent
    write_memory:
      type: rational_memory
  article_write_configs:
    author_num: 1
    citations: 0
    communication_num: 0
    max_refine_round: 1
  env_type: article
  managers:
    article:
      article_dir: data/article
      article_meta_path: data/article_meta_info.pt
      author_path: data/author.pt
      control_profile:
        hub_rate: 0.1
      experiment:
      - shuffle
      generated_article_dir: data/generated_article
      model_config_name: vllm
      retriever_kwargs:
        search_kwargs:
          k: 20
          score_cite: true
        type: graph_vector_retriever
      tool_kwargs:
        filter_keys:
        - big_name
        - topic
        - write_topic
  max_paper_num: 500
  time_configs:
    article_num_per_delta: 5
    author_num_per_delta: 20
    author_time_delta: 5
    cur_time: 2023-05-01
    end_time: 2029-12-01
    round_time_delta: 5
