environment:
  agent:
    llm:
      config_name: gpt-3.5-turbo-0125
    social_memory:
      reflection: false
      summary_threshold: 10
      type: social_memory
    type: article_agent
    write_memory:
      type: rational_memory
  article_write_configs:
    author_num: 5
    citations: 3
    communication_num: 1
    max_refine_round: 1
    use_graph_deg: false
  env_type: article
  managers:
    article:
      article_dir: data/article
      article_meta_path: data/article_meta_info.pt
      author_path: data/author.pt
      control_profile:
        hub_rate: 0
      experiment:
      - shuffle
      generated_article_dir: data/generated_article
      model_config_name: gpt-3.5-turbo-0125
      retriever_kwargs:
        search_kwargs:
          k: 20
          recall_k: 100
          score_cite: false
        type: graph_vector_retriever
      tool_kwargs:
        filter_keys: null
  max_paper_num: 1000
  time_configs:
    article_num_per_delta: 5
    author_num_per_delta: 20
    author_time_delta: 5
    cur_time: 2023-05-01
    end_time: 2029-12-01
    round_time_delta: 5
